-- Add activity types for commission plan workflows
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMISSION_PLAN_CREATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMISSION_PLAN_UPDATED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMISSION_PLAN_ARCHIVED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMISSION_PLAN_ASSIGNED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'COMMISSION_PLAN_ASSIGNMENT_ENDED';
ALTER TYPE "ActivityType" ADD VALUE IF NOT EXISTS 'CAP_LEDGER_UPDATED';
