name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: hatch
          POSTGRES_PASSWORD: hatch
          POSTGRES_DB: hatch_crm
        options: >-
          --health-cmd "pg_isready -U hatch"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://hatch:hatch@localhost:5432/hatch_crm?schema=public
      SHADOW_DATABASE_URL: postgresql://hatch:hatch@localhost:5432/hatch_crm_shadow?schema=public
      REDIS_URL: redis://localhost:6379
      NEXT_PUBLIC_API_URL: http://localhost:4000
      NEXT_PUBLIC_TENANT_ID: tenant-hatch
      NEXT_PUBLIC_DEFAULT_USER_ID: user-agent
      EMAIL_SENDER_DOMAIN: example.hatchcrm.test
      API_HOST: 0.0.0.0
      API_PORT: 4000
      API_WEBHOOK_SECRET: ci-secret
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8.15.4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Generate Prisma client
        run: pnpm --filter @hatch/db generate
      - name: Run migrations
        run: pnpm --filter @hatch/db migrate:dev -- --name ci
      - name: Seed database
        run: pnpm --filter @hatch/db seed
      - name: Lint
        run: pnpm lint
      - name: Unit tests
        run: pnpm test
      - name: Build
        run: pnpm build
